# Generated by Django 4.2.30 on 2026-08-18 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='github_repository',
            field=models.CharField(blank=True, help_text='GitHub repository name (e.g., e_learning_site)', max_length=200),
        ),
    ]
